{{- if or .Values.secret.data .Values.secret.stringData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webapp.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
{{- if .Values.secret.data }}
data:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
{{- if .Values.secret.stringData }}
stringData:
  {{- toYaml .Values.secret.stringData | nindent 2 }}
{{- end }}
{{- end }}
